[package]
name = "md2html"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.69"
pulldown-cmark = { version = "0.8", default-features = false }
wasm-bindgen = "0.2.92"

[dependencies.web-sys]
features = ['Window']
version = "0.3.69"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[package.metadata.wasm-pack.profile.dev]
wasm-opt = ["-Oz", "--enable-mutable-globals"]
